### ISSUE TITLE
use GPS to generate ESDF?

### ISSUE THREAD

**Issue by Anpei2017** [ethz-asl/voxblox#261]
I  used GPS data to generate ESDF directly, but when I use <rosservice call /voxblox_node/save_map ~/t1.voxblox>, the t1.voxblox became executable file. Is it because I didn't give pointcloud to TSDF server?  And, how can I solve it? Thanks!

**Comment by helenol** [comment]
A few points:
 - You can load it again with rosservice call /voxblox_node/load_map ~/t1.voxblox, there is no way to view voxblox map files without the tsdf/esdf server.
 - If you don't put points into the TSDF server, then the map will be blank because voxblox is a dense mapping framework that fuses pointclouds together into a map.

hope that helps!
