### ISSUE TITLE
Ply writer doing something weird

### ISSUE THREAD

**Issue by ToniRV** [ethz-asl/voxblox#293]
I am seeing a very weird behavior when saving a mesh to a `.ply` using the `generate_mesh` rosservice.
When I visualize the mesh in RVIZ, it is clear that the mesh is at positive `y`, while `z` is up.
Yet when I write the mesh I see the values of `y` being the ones of `z`, and the ones of `z` being the ones of `-y`.

1. Here the RVIZ visualization:
![image](https://user-images.githubusercontent.com/9856163/64070728-37530a00-cc36-11e9-9d3a-305ad9be376e.png)

2. Here the mesh loaded in another visualizer:
![image](https://user-images.githubusercontent.com/9856163/64070729-420d9f00-cc36-11e9-91ad-f35444c433c3.png)

3. Here a sample of the ply file: (I had to use cloud compare to convert from binary to ascii to make it readable)

![image](https://user-images.githubusercontent.com/9856163/64070725-299d8480-cc36-11e9-8a56-a803d327372c.png)

**Comment by helenol** [comment]
Are you sure you are visualizing the mesh in the same frame that it is created in? I.e., the "world_frame" frame ID? Because the ply writer really does not do anything special and I really do not see how this would happen:
https://github.com/ethz-asl/voxblox/blob/master/voxblox/include/voxblox/io/ply_writer.h#L72-L98

**Comment by ToniRV** [comment]
Thanks @helenol seems like it was just an intricate combination of frames of reference.
